### ISSUE TITLE
It works very slowly if you try to change the input data

### ISSUE THREAD

**Issue by Osbornnnnn** [yalue/onnxruntime_go#29]
Thanks a lot for the example with float16!!
Problem: I'm trying to start streaming video processing so that it looks for machines, but it takes a very long time to detect by frames
Or how to make it go through 1000 photos of the same size so that it detects the cars on them, but quickly
In Python it works very fast in streaming or by picture

**Comment by Osbornnnnn** [comment]
Maybe use NewDynamicAdvancedSession() but i cant find docs ...

**Comment by yalue** [comment]
Without knowing more about how you're preprocessing the inputs, it's hard to say what's going slowly here.  I wouldn't expect calling `Run()` in a loop to be any slower than running the network in python, if at all.  Are you re-creating the entire session in order to change inputs?  If so, that will certainly be slow.  There are two ways that you can change inputs.

 1. With a regular `AdvancedSession` you can reuse your existing input tensors by writing new data into the tensors' underlying data slices.  Just write your next input into the slice returned by `inputTensor.GetData()`, then call `session.Run()` again.
 2. With a `DynamicAdvancedSession` you can pass new and output tensors to the session every time you call `Run()`.  Unlike `AdvancedSession.Run()`, which always uses the same input and output tensors you passed to `NewAdvancedSession`,  `DynamicAdvancedSession.Run()` takes two arguments: a slice of input tensors, and a slice of output tensors.  (`NewDynamicAdvancedSession()` does not require input and output tensors, though it still requires the list of input and output names.)

The documentation is linked from the project README, and is at https://pkg.go.dev/github.com/yalue/onnxruntime_go

Specifically the documentation on `DynamicAdvancedSession` is at https://pkg.go.dev/github.com/yalue/onnxruntime_go#DynamicAdvancedSession
