### ISSUE TITLE
DirectML support

### ISSUE THREAD

**Issue by aivaki** [yalue/onnxruntime_go#30]
Hi, can you add  [DirectML](https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html) support?

**Comment by aivaki** [comment]
Cool! Is there anything I can do to speed up this process? By the way, `DirectML.dll` is available on any Windows system, so of course I can run a unit test.

**Comment by yalue** [comment]
Oh really? In that case I can probably run a test myself.  I should have checked!  Though I'll post an update here when I have a change ready for you to test as well.

As for timing, chances are I'll have a change ready by this weekend since someone's interested.  However, this is still just a "fun" personal project for me so I can't really guarantee anything---which is why I said a "few weeks."  If I haven't posted a change for testing by this time next week feel free to ping this issue again.

As a preview, though, my plans are something like this:
 1. Copy the struct definition from `dml_provider_factory.h` to `onnxruntime_wrapper.h`, but replace all functions except for `...AppendExecutionProvider_DML` with `void *`s.  As long as the function we care about remains first in the struct, it may even be resilient across minor updates.
 2. Add a wrapper function for enabling DirectML to `onnxruntime_wrapper.h` and `onnxruntime_wrapper.c`.  The implementation in the .c file will first call `ort_api->GetExecutionProviderApi("DML", ORT_API_VERSION, &dml_api_ptr)`.  It can then call `dml_api_ptr->OrtSessionOptionsAppendExecutionProvider_DML(options)`.  If either of these fail, return an error OrtStatus to be handled in Go.
 3. Write a test case and benchmark as with the other execution providers, that are skipped if the function is unsupported.

None of this should be too difficult to pull off, in retrospect.  The main thing I'm not satisfied with is having to copy and modify the `OrtDmlApi` struct definition, even though it _shouldn't_ cause problems.

**Comment by aivaki** [comment]
Ha, I accidentally mentioned this issue. Anyway, thanks for the instructions, I'll try to do it before you do, but I can't guarantee the result.

**Comment by yalue** [comment]
Adding the code went easily enough, so I tried to take care of it already.  If you have time, I'd appreciate it if you felt like checking out the `add_directml_support` branch, running `go test -v -bench=.`, and making sure the DirectML tests pass rather than get skipped.  I tried running it on my own system, but the DirectML functions would report a `The specified device interface or feature level is not supported on this system.` error.  Assuming you already have a working DirectML-supporting onnxruntime build, I'd be happy for help with testing, since I'm fairly confident the code I added should work.

**Comment by aivaki** [comment]
I tried to run test with yours `onnxruntime.dll` and got
```
=== RUN   TestDirectMLSession
    onnxruntime_test.go:1116: Couldn't enable DirectML: Specified provider is not supported.. This may be due to your system or onnxruntime library version not supporting DirectML.
--- SKIP: TestDirectMLSession (0.07s)
```

Then I download [Microsoft.ML.OnnxRuntime.DirectML.1.16.3.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.16.3/Microsoft.ML.OnnxRuntime.DirectML.1.16.3.zip ), taking from here `onnxruntime.dll ` and replacing the existing one
```
=== RUN   TestDirectMLSession
--- PASS: TestDirectMLSession (3.31s)
```

**Comment by aivaki** [comment]
I notice that Windows 11 (Build 10.0.22621; 22H2) is still only have [DirectML-1.8.0](https://www.nuget.org/packages/Microsoft.AI.DirectML/1.8.0) included but we need a newer version.
For more information see https://learn.microsoft.com/en-us/windows/ai/directml/dml-version-history

**Comment by yalue** [comment]
Sounds great, thank you for checking!  Yes, I figured you'd need to download the DirectML-enabled build in order to run this, and I'm not surprised at the strict version requirements.  (All of my machines are Windows 10, so it makes sense they wouldn't work for me.)  The test code checks the `ONNXRUNTIME_SHARED_LIBRARY_PATH` environment variable for a different path if you want to use a version of `onnxruntime.dll` other than the one in the `test_data` directory.  I use this myself when testing CUDA and TensorRT support, since I don't want to include copies of the (much larger) GPU-enabled onnxruntime shared libraries in this repo.

Did you get a chance to run the benchmark as well?  (`go test -v -bench=.`)  It can be a good sanity check to make sure that the accelerated execution provider is actually running faster than the CPU.  I'll probably merge PR #32 later today if you don't encounter any problems.

**Comment by aivaki** [comment]
I've already tried this new branch in my project, it works really well.

`go test -v -bench="."`
```
goos: windows
goarch: amd64
pkg: ort
cpu: AMD FX(tm)-6300 Six-Core Processor
BenchmarkOpSingleThreaded
BenchmarkOpSingleThreaded-6            1        6226565400 ns/op
BenchmarkOpMultiThreaded
BenchmarkOpMultiThreaded-6             1        4540012800 ns/op
BenchmarkCUDASession
    onnxruntime_test.go:977: Error creating CUDA provider options: CUDA execution provider is not enabled in this build.. Your version of the onnxruntime library may not support CUDA. Skipping the remainder of this test.
--- SKIP: BenchmarkCUDASession
BenchmarkTensorRTSession
    onnxruntime_test.go:1030: Error creating TensorRT provider options; TensorRT execution provider is not enabled in this build.. Your version of the onnxruntime library may not include TensorRT support. Skipping the remainder of this test.
--- SKIP: BenchmarkTensorRTSession
BenchmarkCoreMLSession
    onnxruntime_test.go:1084: Couldn't enable CoreML: Your platform or onnxruntime library does not support CoreML. This may be due to your system or onnxruntime library version not supporting CoreML.
--- SKIP: BenchmarkCoreMLSession
BenchmarkDirectMLSession
BenchmarkDirectMLSession-6             1        1508222600 ns/op
PASS
ok      ort     23.676s
```

**Comment by yalue** [comment]
Excellent, looks like a 3x speedup on the arbitrary benchmark (which just multiplies and divides a 200MB tensor by scalars several times in a row).  Thanks again for the help!  I merged the change, and will probably bump the minor version after I address #31.
