### ISSUE TITLE
Getting input and output names from a model

### ISSUE THREAD

**Issue by aivaki** [yalue/onnxruntime_go#31]
Just look at [peer-ai-org/onnxruntime_go/onnxruntime_wrapper.c](https://github.com/peer-ai-org/onnxruntime_go/blob/aa11a59967d0dcf1225784eafd407df27c49bae0/onnxruntime_wrapper.c#L132) and [peer-ai-org/onnxruntime_go/onnxruntime_go_v3_newsession.go](https://github.com/peer-ai-org/onnxruntime_go/blob/aa11a59967d0dcf1225784eafd407df27c49bae0/onnxruntime_go_v3_newsession.go#L107). I can't find something like this (I've already seen #22, but it doesn't have a solution), so could you add this? That would be great.

**Comment by yalue** [comment]
Sure, I can probably add this.  It should be easy enough to add to `AdvancedSession` and `DynamicAdvancedSession` without breaking API compatibility.

**Comment by yalue** [comment]
This should now be possible as of commit d7e65a16dc633f9416, and tagged version v1.7.0.  I added two new functions:
- `inputs, outputs, err := GetInputOutputInfo("path/to/file.onnx")`, or
- `inputs, outputs, err := GetInputOutputInfoWithONNXData(onnxByteSlice)`
Either function returns two slices of `InputOutputInfo` structs, which contains the name, shape, and type of each input and output.

Ultimately, I decided that there wasn't much point to adding this information the `AdvancedSession` type itself, since the `AdvancedSession` APIs already require specifying input names.  I would need to change this to allow users to not specify input names ahead of time, basically forcing users to create a useless `AdvancedSession` just in order to let users read input and output info.  It seemed cleaner to provide the same information with a function that creates and destroys a `C.OrtSession` internally.

Hopefully this also addresses #22.
