### ISSUE TITLE
Compile a Go program with a static build of ONNX Runtime

### ISSUE THREAD

**Issue by carlesoctav** [yalue/onnxruntime_go#42]
I’m new to CGO (C-Go binding) things. What I want to ask is whether it’s possible to compile a Go program with a static build of ONNX Runtime ( using a .a binary instead of a .so shared library).

**Comment by yalue** [comment]
Hi, and thanks for the question.  It think that it _is_ possible to link a Go program against a static build of onnxruntime, but not with this respository.  Unfortunately, you'll quickly hit issues when you try to use static onnxruntime builds with Go on Windows, due to onnxruntime on Windows always assuming the usage of MSVC, while Go requires mingw.  Since I wanted to make these bindings work on Linux and Windows, I do additional work to ensure that I never need to link against any static onnxruntime libraries.

Since you're mentioning .a files, I'm assuming you're wanting to use Linux.  Fortunately there seem to be other onnxruntime Go bindings for that use case.  For example, https://github.com/ivansuteja96/go-onnxruntime seems somewhat recent, and claims to support both Linux and macOS.  Good luck!
