### ISSUE TITLE
Batch inference has no performance improvement

### ISSUE THREAD

**Issue by rathoddeepak** [yalue/onnxruntime_go#45]
```
func runInference(modelSes ModelSession, inputs [][]float32) ([][]float32, error) {

	batchSize := len(inputs)
    if batchSize == 0 {
        return nil, errors.New("empty input batch")
    }

    inputTensorData := modelSes.Input.GetData()
    for i, input := range inputs {
        offset := i * len(input)
        copy(inputTensorData[offset:], input)
    }

    t := time.Now();

    err := modelSes.Session.Run()
    if err != nil {
        return nil, err
    }

    fmt.Printf("Time Taken: %s\n", time.Since(t))

    outputData := modelSes.Output.GetData()
    outputSize := len(outputData) / batchSize
    outputs := make([][]float32, batchSize)
    for i := 0; i < batchSize; i++ {
        start := i * outputSize
        end := start + outputSize
        outputs[i] = outputData[start:end]
    }

    return outputs, nil
}

```

This provides 60-65ms for 3 images when batched together
And is same for single image inference 3 times 

Please help!!

Use 

mac m1 
coreml enabled

```
inputShape := ort.NewShape(inputSize, 3, 640, 640)
	inputTensor, err := ort.NewTensor(inputShape, make([]float32, 9830400))
	// inputTensor, err := ort.NewTensor(inputShape, input)
	if err != nil {
		return ModelSession{}, err
	}

	// outputShape := ort.NewShape(1, 84, 8400)
	outputShape := ort.NewShape(inputSize, 84, 8400)
	outputTensor, err := ort.NewEmptyTensor[float32](outputShape)
	if err != nil {
		return ModelSession{}, err
	}

	options, e := ort.NewSessionOptions()
	if e != nil {
		return ModelSession{}, err
	}

	if UseCoreML { // If CoreML is enabled, append the CoreML execution provider
		e = options.AppendExecutionProviderCoreML(0)
		if e != nil {
			fmt.Println("UseCoreML failed", err)
			options.Destroy()
			return ModelSession{}, err
		}		
	}
	defer options.Destroy()

	session, err := ort.NewAdvancedSession(ModelPath,
		[]string{"images"}, []string{"output0"},
		[]ort.ArbitraryTensor{inputTensor}, []ort.ArbitraryTensor{outputTensor}, options)

	if err != nil {
		return ModelSession{}, err
	}

	modelSes := ModelSession{
		Session: session,
		Input:   inputTensor,
		Output:  outputTensor,
	}

	return modelSes, err
```

**Comment by yalue** [comment]
Hi, and thank you for the question.  Unfortunately, this simply seems to be a question of hardware capabilities or the network architecture, and therefore entirely out of the control of the framework itself.  For example, is inference any faster when running in batched mode when using the `onnxruntime` library from a python script?  Additionally, simply using batched inference does not necessarily make inference more efficient---especially if a single image already fully occupies the CPU or accelerator.  Batching only helps reduce launch overheads and make better use of underutilized hardware.  The overhead of 3 calls to `Run()` should barely make a difference with a 50+ms overall run time, so it's not much of a surprise that a single call to `Run()` has little impact.

I will close this issue, since I doubt this is pertinent to the Go wrapper specifically.  However, if you re-run your test using a python script and find it significantly faster with a 3-batch than with 3 separate calls to `Run()` feel free to re-open it and include more details about the performance you see in python---I expect it to be similar to the performance of the Go wrapper, so a significant disparity would be good evidence of an underlying issue.  Unfortunately, simply a lack of clear benefit to batching on inference does not necessarily imply an issue here.

Thanks!
