### ISSUE TITLE
Session destroy not free memory as  expected

### ISSUE THREAD

**Issue by FelixHo** [yalue/onnxruntime_go#48]
The code below will consecutively load multiple models and immediately destroy them after each load. From the output, it is evident that the memory was not completely freed as expected.

model file here:
[example_lgb.onnx.zip](https://github.com/yalue/onnxruntime_go/files/14850089/example_lgb.onnx.zip)

code:
```golang
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"

	ort "github.com/yalue/onnxruntime_go"
)

func main() {
	fmt.Println("~~~~~ START :" + CurrentMemoryUsage())

	ort.SetSharedLibraryPath("/path/to/lib")
	ort.InitializeEnvironment()

	fmt.Println("~~~~~ InitializeEnvironment :" + CurrentMemoryUsage())

	modelPath := "./example_lgb.onnx"
	for i := 0; i < 10; i++ {
		sess, _ := ort.NewDynamicAdvancedSession(modelPath, []string{"input"}, []string{"probabilities", "label"}, nil)
		sess.Destroy()
		fmt.Println(fmt.Sprintf("~~~~~~ After DestroySession-%d: ", i) + CurrentMemoryUsage())
	}

	ort.DestroyEnvironment()

	fmt.Println("~~~~~~ After DestroyEnvironment: " + CurrentMemoryUsage())

}

func CurrentMemoryUsage() string {
	pid := strconv.Itoa(os.Getpid())

	cmd := exec.Command("ps", "-p", pid, "-o", "rss=")
	var out bytes.Buffer
	cmd.Stdout = &out
	err := cmd.Run()
	if err != nil {
		fmt.Printf("Failed to run command: %v\n", err)
		return ""
	}

	output := strings.TrimSpace(out.String())
	memUsage, err := strconv.Atoi(output)
	if err != nil {
		fmt.Printf("Failed to parse memory usage: %v\n", err)
		return ""
	}

	return fmt.Sprintf("current memory usage: %d MB\n", memUsage/1024)
}

```

output:
```
~~~~~ START :current memory usage: 8 MB

~~~~~ InitializeEnvironment :current memory usage: 20 MB

~~~~~~ After DestroySession-0: current memory usage: 55 MB

~~~~~~ After DestroySession-1: current memory usage: 66 MB

~~~~~~ After DestroySession-2: current memory usage: 78 MB

~~~~~~ After DestroySession-3: current memory usage: 87 MB

~~~~~~ After DestroySession-4: current memory usage: 91 MB

~~~~~~ After DestroySession-5: current memory usage: 102 MB

~~~~~~ After DestroySession-6: current memory usage: 111 MB

~~~~~~ After DestroySession-7: current memory usage: 123 MB

~~~~~~ After DestroySession-8: current memory usage: 124 MB

~~~~~~ After DestroySession-9: current memory usage: 125 MB

~~~~~~ After DestroyEnvironment: current memory usage: 125 MB
```

If I don't run destroy, memory use goes up, as expected. But when I do run destroy, memory isn't fully freed. Am I missing something?

ps: 
> go version go1.20.12 darwin/arm64
> onnxruntime 1.16.3
> onnxrumtime_go 1.8.0

**Comment by yalue** [comment]
It's possible that this is simply due to Go's garbage collector not relinquishing memory back to the operating system quickly enough.  The onnxruntime_go library shouldn't be allocating much memory on its own.  So there are two possibilities here, as I see it:

 - The memory used to hold a copy of the .onnx file isn't being garbage collected
 - The memory used to hold a copy of the .onnx file is being garbage collected but not returned to the host OS
 - The onnxruntime library itself is allocating memory that it doesn't relinquish.

I'll investigate further if I get a chance.  One thing you may try is putting a call to `runtime.GC()` at the end of every loop, after `Destroy`-ing a session.  This should manually invoke the garbage collector.

**Comment by yalue** [comment]
After more investigation, I will now say this is almost certainly normal behavior from Go's garbage collector.  I modified your example in two ways:
 - I added a call to `runtime.GC()` after `sess.Destroy()` to manually prompt Go to invoke its garbage collector
 - I ran the loop for 100 iterations rather than 10.

After doing this, the reported memory usage capped out at 185 MB (on my test system).  On other runs it was more or less. In some cases the reported memory even went down.  It's just a case of the garbage collector holding onto more pages that it needs.  Let me know if you see further problems!

Also, here are the last few lines of output when I inserted `runtime.GC()` and ran 100 iterations:
```
...
~~~~~~ After DestroySession-78: current memory usage: 185 MB

~~~~~~ After DestroySession-79: current memory usage: 185 MB

~~~~~~ After DestroySession-80: current memory usage: 185 MB

~~~~~~ After DestroySession-81: current memory usage: 185 MB

~~~~~~ After DestroySession-82: current memory usage: 185 MB

~~~~~~ After DestroySession-83: current memory usage: 185 MB

~~~~~~ After DestroySession-84: current memory usage: 185 MB

~~~~~~ After DestroySession-85: current memory usage: 185 MB

~~~~~~ After DestroySession-86: current memory usage: 185 MB

~~~~~~ After DestroySession-87: current memory usage: 185 MB

~~~~~~ After DestroySession-88: current memory usage: 185 MB

~~~~~~ After DestroySession-89: current memory usage: 185 MB

~~~~~~ After DestroySession-90: current memory usage: 185 MB

~~~~~~ After DestroySession-91: current memory usage: 185 MB

~~~~~~ After DestroySession-92: current memory usage: 185 MB

~~~~~~ After DestroySession-93: current memory usage: 185 MB

~~~~~~ After DestroySession-94: current memory usage: 185 MB

~~~~~~ After DestroySession-95: current memory usage: 185 MB

~~~~~~ After DestroySession-96: current memory usage: 185 MB

~~~~~~ After DestroySession-97: current memory usage: 185 MB

~~~~~~ After DestroySession-98: current memory usage: 185 MB

~~~~~~ After DestroySession-99: current memory usage: 183 MB

~~~~~~ After DestroyEnvironment: current memory usage: 170 MB
```
