### ISSUE TITLE
onnxruntime training

### ISSUE THREAD

**Issue by riccardopinosio** [yalue/onnxruntime_go#52]
I am wondering whether it would be possible to add support for onnxruntime training to onnruntime_go. It would be particularly interesting to be able to train models on user feedback on device. Would it be something you would consider as an addition? I believe it could be done with bindings to onnxruntime training, see https://onnxruntime.ai/docs/install/#training-phase---on-device-training

**Comment by yalue** [comment]
It looks like you're correct in that there's a C API so it should be possible to add Go bindings ([C API example in docs](https://onnxruntime.ai/docs/api/c/training_c_cpp_api.html)).  However, it looks like it would be a significant addition, since I would need to add another header, another Session type, and bindings for every function in [the training C API header](https://github.com/microsoft/onnxruntime/blob/main/orttraining/orttraining/training_api/include/onnxruntime_training_c_api.h).  On top of that, for the training API to be easy to test, the .shared libraries in `test_data/` would need to be swapped out for the versions that include training support.  This, of course, is doable, but I'm already not happy with how large the test_data directory has become.  So, some thought would need to be given to how to make the tests work OK.  (Though on the other hand, the `test_data/` libraries already don't support CUDA, so I suppose there's precedent for skipping tests here.)

Honestly, that all seems doable enough---though the other issue is that I am unlikely to use it personally.  So, I suppose my stance is that I'd be happy to review a PR if someone else is willing to do a lot of the work!  Here are the things that I would want to see in a potential PR:

 - A new .go file for the bindings, say `training_api.go`.
     - This would contain a `TrainingSession` type that would follow the style of `AdvancedSession`
     - This would also invoke all of the C API functions.
     - We'd want something like `func TrainingSupported() error` that returns an error if the training API is not supported in the shared library.
 - `onnxruntime_wrapper.c` and `onnxruntime_wrapper.h` would need to expose pure C functions.
     - A `static const OrtTrainingApi *training_api;` would need to be added to `onnxruntime_wrapper.c` similar to the current `static const OrtApi`.
     - `SetApiFromBase` (in `onnxruntime_wrapper.c`) could be modified to attempt to call `ort_api->GetTrainingApi(ORT_API_VERSION)`.  This returns NULL if training isn't supported.
     - Every function that uses the training API _must_ check that `training_api` is not NULL---I want to make it completely impossible to cause a segfault from attempting to use the training API in Go.  (It's probably better to just use the `TrainingSupported` go function I mentioned above.)
 - A new test file for the bindings, like `training_api_test.go`
     - These unit tests should skipped if the training API isn't supported in the version of `onnxruntime.so` in `test_data/` or indicated by the `ONNXRUNTIME_SHARED_LIBRARY_PATH` environment variable used by the other tests.
     - A _minimal_ test case that would be easy to validate.  For example, I'd want to have a unit test that would train a small network to add two inputs.  The test would need to use the training API to create and train the network, then test it on a bunch of outputs to make sure it's fairly close to the expected behavior.
     - A basic benchmark test (run via `go test -v -bench=.`), similar to what I have with `BenchmarkCUDASession` in `onnxruntime_test.go`.  I'd want a benchmark for training using both CUDA and plain CPU.
 - Adding the `onnxruntime_training_c_api.h` header---but nothing else.  I don't want to start copying entire `include/` directories from `onnxruntime`.  (And no C++ anywhere.)
 - Being a larger change, I'd be more picky that the code matches my personal style---so religiously following `gofmt`, plus 80-character lines.

**Comment by riccardopinosio** [comment]
Ok, clear. I am interested in using this capability from go, so I might give it a try to implement this bit.
