### ISSUE TITLE
build constraints exclude all Go files in

### ISSUE THREAD

**Issue by Yukitaka2115** [yalue/onnxruntime_go#53]
I came across github.com/yalue/onnxruntime_go when compiling:  build constraints exclude all Go files in C:\Users\41572\go\pkg\mod\github.com\yalue\onnxruntime_go@v1.9.0

**Comment by Yukitaka2115** [comment]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\41572\go #gosetup
"C:\Program Files\Go\bin\go.exe" build -o C:\Users\41572\AppData\Local\JetBrains\GoLand2024.1\tmp\GoLand\___go_build_object_detector.exe object_detector #gosetup
github.com/yalue/onnxruntime_go: build constraints exclude all Go files in C:\Users\41572\go\pkg\mod\github.com\yalue\onnxruntime_go@v1.9.0****
wrong like this

**Comment by yalue** [comment]
I'm still afraid that's not enough information for me to understand or reproduce the problem.  I highly doubt this is an issue with onnxruntime_go specifically for a simple reason: I only use build constraints in two go files: `setup_env.go` and `setup_env_windows.go`.  (The latter is configured to only be built on Windows.)  However, there are no build constraints in `onnxruntime_go.go` or `legacy_types.go`.

So I don't see how the build constraints used in this project can possibly exclude all Go files.  Could this be an issue with cgo?  Is cgo enabled in your version of Go?  If so, that could explain the issue you are having.  It also looks like people have had similar issues due to caching issues using Goland: https://stackoverflow.com/a/73531307

**Comment by Yukitaka2115** [comment]
solved thx!

**Comment by leopku** [comment]
> solved thx!

Same issue.

@Yukitaka2115 Could you plz share how to fixed? thanks.

**Comment by leopku** [comment]
Thank you @tphakala .
I installed clang and test again,   `build constraints exclude all Go files`  disapeared.

Next time  I  will try MinGW-w64 because there were still some issue about Clang env.

BTW: Happy new year, guys.
