### ISSUE TITLE
Question: Are Sci-Kit Learn Models supported by this library?

### ISSUE THREAD

**Issue by jacksteussie** [yalue/onnxruntime_go#65]
As in the title. I'm just wondering if these are supported, sorry if it's a stupid question, I'm kind of new to ORT.

**Comment by yalue** [comment]
No, it's a reasonable question, because those models do have unconventional output formats.  However, I'm happy to say that I added support for them a couple weeks ago.  You can see an example here: https://github.com/yalue/onnxruntime_go_examples/tree/master/non_tensor_outputs

That example just runs the network copied from the random forest example on the sklearn website.  (See `generate_sklearn_network.py` in the repo linked above.)  Unfortunately, accessing the particular output formats in Go is not very convenient.  The `non_tensor_outputs.go` file in the same directory shows how to load the resulting .onnx file, run it, and process its outputs.  It has two outputs: one of them is a straightforward int64 tensor, but the other is an ONNX sequence of ONNX maps.

If you are truly new to onnxruntime, there are other examples in the `onnxruntime_go_examples` repo that you may find easier.  Or, alternatively, I often recommend getting familiar with the `onnxruntime` python library if you're completely new, since that's probably faster to experiment with.

Finally, if you find a sklearn-generated model that works using `onnxruntime` in python but is unsupported by this library, feel free to open an issue.  Good luck!
