### ISSUE TITLE
onnx model with external data

### ISSUE THREAD

**Issue by riccardopinosio** [yalue/onnxruntime_go#67]
Currently session creation fails for onnx models with external data (i.e. any model larger than 2GB) in linux-x64.

For instance, trying to get input/output info for the following model: https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-onnx/tree/main/cpu_and_mobile/cpu-int4-rtn-block-32 when saved inside a subfolder:

```
SetSharedLibraryPath("/lib64/onnxruntime.so")
err := InitializeEnvironment()
if err != nil {
	t.Fatal(err)
}
defer DestroyEnvironment()
inputs, _, err := GetInputOutputInfo("Microsoft_Phi-3-mini-4k-instruct-onnx/phi3-mini-4k-instruct-cpu-int4-rtn-block-32.onnx")
if err != nil {
	t.Fatal(err)
}
```

One gets:

```
--- FAIL: TestLoadExternal (0.05s)
onnxruntime_test.go:1524: Error getting inputs and outputs from Microsoft_Phi-3-mini-4k-instruct-onnx/phi3-mini-4k-instruct-cpu-int4-rtn-block-32.onnx: Error creating temporary session: Deserialize tensor model.layers.32.final_norm_layernorm.weight failed.GetFileLength for ./phi3-mini-4k-instruct-cpu-int4-rtn-block-32.onnx.data failed:Invalid fd was supplied: -1
FAIL
```

I could only make this work by ensuring that the .data file is in the current working directory, as onnx by default seems to check from there based on the harcoded relative path in the onnx file.

It would be nice if this was handled by onnxruntime_go however. The only idea I have at the moment is to temporarily change the cwd to the directory containing the onnx file when creating a session so that onnx can find the data file.

**Comment by yalue** [comment]
Thanks for raising this issue, as I have never tried to load a file with external data.  Unfortunately, even the C API for supplying external data is very clunky to use (see `AddExternalInitializers` or `AddExternalInitializersFromFilesInMemory` in `onnxruntime_c_api.h`), so I doubt there will be a "clean" approach in Go.  I'm actually fine with temporarily setting the cwd when creating the session.  If you or someone else wants to work on a change for this, I'd be happy to take a look at it.

At a quick glance, this is what I would suggest:

1. Modify the go `SessionOptions` struct to have a field such as `workingDirDuringLoad` or something like that (there's got to be a better name).
2. Add a setter function to SessionOptions, such as `SetTemporaryCWDForLoading` that sets the field.
3. Modify the `createCSession` function to something like this:
    ```go
	// ...
	var ortSession *C.OrtSession
	var ortSessionOptions *C.OrtSessionOptions
	var tempWorkingDir string
	if options != nil {
		ortSessionOptions = options.o
		tempWorkingDir = options.workingDirDuringLoad
	}
	if tempWorkingDir != "" {
		prevDir, e := os.Getwd()
		if e != nil {
			return nil, fmt.Errorf("Error getting previous working dir: %w", e)
		}
		e = os.Chdir(tempWorkingDir)
		if e != nil {
			return nil, fmt.Errorf("Error setting temp working dir: %w", e)
		}
		defer os.Chdir(prevDir)
	}
	status := C.CreateSession(unsafe.Pointer(&(onnxData[0])),
		C.size_t(len(onnxData)), ortEnv, &ortSession, ortSessionOptions)
	// ...
    ```
 4. Somehow modify the `GetInputOutputInfo` and `GetModelMetadata` functions to pass the directory containing the `.onnx` file down the stack to `createCSession`.  This will be a bit annoying, because I don't want to change the signature for the `...WithONNXData` variants of these functions.  (Similarly, I don't want to call the C API functions that take a path due to the windows compatibility headache.  Maybe it's time to just figure out a clean way to convert UTF-8 to UTF-16 strings when using the windows APIs...)

**Comment by riccardopinosio** [comment]
hi, it seems a bit diffcult to pass down the `.onnx` directory to the `withOnnxData` functions without modifying their signature. The only solution I can think of is to add functions:

```
withOnnxDataAndOptions(data []byte, options SessionOptions)
```

which essentially duplicate the `withOnnxData` function but with options. Then the `GetInputOutputInfo` can switch to this function internally, but the `withOnnxData` functions remain intact.
How do you feel about this workaround?

**Comment by yalue** [comment]
Does this problem still persist after commit b5a29a1390f985830891 (PR #69)?  After that commit, the `CreateSession` APIs should be taking file paths directly rather than using file buffers, so I'm hoping that allows onnxruntime to find external data more easily.

**Comment by riccardopinosio** [comment]
great stuff will check later

**Comment by yalue** [comment]
Quick update: when I get a chance, I think I will be able to make a small test case by following the "Converting an ONNX Model to External Data" instructions from [this page](https://onnx.ai/onnx/repo-docs/ExternalData.html).  I hope I can make a sub-4KB .onnx file with external data, and write a quick test case.

**Comment by yalue** [comment]
Over a month later, I finally ran the test.  Unfortunately, all I managed to do was confirm the same issue.  It seems like a problem with onnxruntime itself.  Onnx indicates that external data should be detected if it's in the same directory as the model file:

>  If the external data is under the same directory of the model, simply use `onnx.load()`

(From [here](https://onnx.ai/onnx/repo-docs/ExternalData.html))

However, onnxruntime seems to interpret "the same directory as the model file" as "the current working directory."  Which simply seems incorrect to me, but people have brought this issue up before and they don't seem likely to do anything to address it.

I don't really know how to work around this.  Even if I add bindings to the (extremely clunky) C API for loading external data, one would still need to call an additional function and somehow provide the function the path to the external data. (in other words, no less work than just `cd`ing into the directory containing the data)

So, I think I am unlikely to be able to fix this myself.  The ideal solution would be onnxruntime actually respecting the "same directory of the model" mentioned in the onnx spec.  For what it's worth, the official python onnxruntime bindings also fail to load a `.onnx` with external data from somewhere other than the current working directory.  So, I think I'll just be in line with the python bindings here and leave this issue on users to address by changing directories prior to creating the session.  I apologize for this, but feel free to re-open the issue if you have a better solution in mind!
